import styles from './page.module.css';
import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';

const inter = Noto_Sans({ weight: ['100', '300', '400', '500', '700'], subsets: ['cyrillic'] });

export const metadata: Metadata = {
  title: 'Top-App - рейтинги',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang='ru'>
      <head></head>
      <body className={inter.className}>
        <nav className={styles.nav}>
          <ul>
            <li>Курсы</li>
            <li>Второе</li>
            <li>Третье</li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}







